---
dgx_provision_firmware_check: true
dgx_provision_bios_settings:
  SR-IOV: "Enabled"
  IOMMU: "Enabled"
  BootMode: "UEFI"
dgx_provision_gpu_driver_version: latest
dgx_provision_network_interfaces: []
dgx_provision_validate_certs: true
dgx_provision_wait_timeout: 1800
