---
galaxy_info:
  role_name: virtual_media_boot
  namespace: stevefulme1
  author: Steve Fulmer
  description: DGX provisioning via virtual media
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "9"
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - nvidia
    - dgx
    - gpu
    - ai
dependencies: []
