---
galaxy_info:
  role_name: reference_deployment
  namespace: stevefulme1
  author: Steve Fulmer
  description: Deploy AI Factory reference architecture
  company: Red Hat
  license: GPL-3.0-or-later
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "9"
    - name: Ubuntu
      versions:
        - jammy
  galaxy_tags:
    - deployment
    - reference_architecture
    - ai
    - gpu
dependencies: []
